### ISSUE TITLE
Device : Poco M3

### ISSUE THREAD

**Issue by crossdefalt** [whyakari/TermuxDisableProcces#1]
```
~ $  adb shell settings put global settings_enable_monitor_phantom_procs false

Exception occurred while executing 'put':
java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
        at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2272)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1439)
        at com.android.providers.settings.SettingsProvider.insertGlobalSetting(SettingsProvider.java:1393)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:450)
        at android.content.ContentProvider.call(ContentProvider.java:2486)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:517)
        at com.android.providers.settings.SettingsService$MyShellCommand.putForUser(SettingsService.java:382)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:278)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:50)
        at android.os.Binder.shellCommand(Binder.java:953)
        at android.os.Binder.onTransact(Binder.java:837)
        at android.os.Binder.execTransactInternal(Binder.java:1187)
        at android.os.Binder.execTransact(Binder.java:1146)
```

**Comment by crossdefalt** [comment]
![Screenshot_2023-01-31-21-45-38-217_com android settings](https://user-images.githubusercontent.com/106070707/215817589-92477188-cbd9-49d9-b1ee-075e319b0f28.jpg)
I guess i am missing this USB debug security setting to turn on for that i need to put a simcard. I will later thanks .
